### ISSUE TITLE
Failed to resolve: ultimatebarx-0.3.2

### ISSUE THREAD

**Issue by himno** [Zackratos/UltimateBarX#17]
添加最新版本的时候报错，旧版本0.3.1没问题，搞不懂啊大佬
Gradle版本4.1.1
kotlin版本1.4.21

**Comment by Zackratos** [comment]
我这边试了是正常的啊，是不是你的网络问题，换个网络试一下？

**Comment by himno** [comment]
> 
> 
> 我这边试了是正常的啊，是不是你的网络问题，换个网络试一下？

嗯，可能是阿里源没有把最新的版本同步过去。我换回官方源，挂代理重新试了下，就可以了。
