### ISSUE TITLE
会造成布局抖动，旧版的比较不明显

### ISSUE THREAD

**Issue by WU1208** [Zackratos/UltimateBarX#2]
<LinearLayout>

<View1
android:layout_weight="1"/>

<View2 />

</LinearLayout>
布局大概如上所示，打开后，View2 会有一个明显的向上移动到应该在的地方，感觉是因为开始的时候被导航栏往上顶上去的

**Comment by Zackratos** [comment]
第一次设置是会有抖动的，因为要改变 View 的 margin 和 padding，旧版的因为用的是 setFitsSystemWindows 方法，不需要改变 margin 和 padding ，所以不明显，但是旧版的有很大的缺陷
