### ISSUE TITLE
状态栏设置light模式不生效

### ISSUE THREAD

**Issue by Masksam** [Zackratos/UltimateBarX#20]
```
implementation 'com.zackratos.ultimatebarx:ultimatebarx:0.3.3'

ROM ： MIUI 11

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_home);
    UltimateBarX.with(this).light(false).applyStatusBar();

...
}
```

**Comment by Zackratos** [comment]
`light(true)` 才是 light 模式（状态栏字体变灰色）

**Comment by zhaoxiuyu** [comment]
需要配置混淆文件不 @Zackratos

**Comment by Masksam** [comment]
> `light(true)` 才是 light 模式（状态栏字体变灰色）

是的，我设置了 false  无效

**Comment by Zackratos** [comment]
> > `light(true)` 才是 light 模式（状态栏字体变灰色）
> 
> 是的，我设置了 false 无效

设置了 false ，然后变灰色了吗？你是啥手机

**Comment by Zackratos** [comment]
> 需要配置混淆文件不 @Zackratos

应该不需要

**Comment by Masksam** [comment]
> 设置了 false ，然后变灰色了吗？你是啥手机


![微信图片_20201223113853](https://user-images.githubusercontent.com/18209000/102956774-b519e380-4513-11eb-89e9-77c35965efb1.jpg)
```
设置 UltimateBarX.with(this).light(false).applyStatusBar();后就这样了
机型 ： 小米8  Android 10.0  MIUI 11
```

**Comment by Zackratos** [comment]
> > 设置了 false ，然后变灰色了吗？你是啥手机
> 
> ![微信图片_20201223113853](https://user-images.githubusercontent.com/18209000/102956774-b519e380-4513-11eb-89e9-77c35965efb1.jpg)
> 
> ```
> 设置 UltimateBarX.with(this).light(false).applyStatusBar();后就这样了
> 机型 ： 小米8  Android 10.0  MIUI 11
> ```

这是正常的，因为你没有设置状态栏颜色，就是默认的 `colorPrimaryDark` 的颜色，你的应该是白色或透明，然后你用 `light(false)` 就是不让状态栏字体变灰色，状态栏字体是白色，状态栏也是白色，就会看不见了，不知道你想要什么效果，如果你要改变状态栏本身的颜色，可以用 `color` 方法或者 `colorRes` 方法或者 `drawableRes` 方法，如果你要让状态栏字体变灰色，你应该调用 `light(true)`，可以仔细看看 demo 的写法，如果还有疑问，可以加我微信 `kratosbruce` 交流
