### ISSUE TITLE
底部导航栏重叠问题

### ISSUE THREAD

**Issue by yunnec** [Zackratos/UltimateBarX#21]
当在全面屏模式下开启手势提示线时，导航栏会和布局重叠。
demo的效果如下：
![AirPlay_Screenshot_2020-12-22_07-18-40](https://user-images.githubusercontent.com/28297534/102883402-f0240480-448a-11eb-9ee8-c7dd7085f8fd.png)
![AirPlay_Screenshot_2020-12-22_07-17-28](https://user-images.githubusercontent.com/28297534/102883427-f87c3f80-448a-11eb-93f2-6826715d2ab4.png)

机型：Redmi note 8 pro

**Comment by Zackratos** [comment]
这个主要是因为无法判断手势提示线是否开启，暂时无法解决

**Comment by Zackratos** [comment]
用骚操作解决了这个问题，亲测有效，可以用最新的 0.4.1 版本 @yunnec
