### ISSUE TITLE
基类调用无效果

### ISSUE THREAD

**Issue by OneUserName** [Zackratos/UltimateBarX#22]
基类里面调用没有效果

 class MainActivity : BaseActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .replace(R.id.fragmetn_container, MainFragment())
                .commitNow()
        }
    }
}

open class BaseActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initStatusBar()
    }

    protected fun initStatusBar() {
        UltimateBarX.with(this)
                .fitWindow(true)
//                .color(Color.RED)             // 状态栏背景颜色（色值）
                .colorRes(R.color.main_theme_color)     // 状态栏背景颜色（资源id）
//                .drawableRes(R.mipmap.user_center_top_nav_bg)
//                .light(false)
                .applyStatusBar()
    }

}

**Comment by Zackratos** [comment]
在 `onViewCreated` 方法里调用
