### ISSUE TITLE
使用透明状态栏后问题

### ISSUE THREAD

**Issue by R29kTA** [Zackratos/UltimateBarX#23]
我是初学者，我仅在activity中使用 UltimateBarX.with(this)
            .transparent()
            .applyStatusBar()
后，发现toolbar（整体布局都）上移了
![image](https://user-images.githubusercontent.com/35038406/103254609-f2252080-49c0-11eb-9d49-2341f0a19460.png)
这样。
这是正常的
![image](https://user-images.githubusercontent.com/35038406/103254473-6612f900-49c0-11eb-9c27-b8479d5a8907.png)

**Comment by Zackratos** [comment]
你这种应该不要让状态栏透明，给状态栏设置一个背景色，然后不让布局侵入到状态栏，代码如下
```kotlin
UltimateBarX.with(this)
    .fitWindow(true)
    .color(Color.BLUE)
    .applyStatusBar()
```
可以好好看看 demo 中各种效果的写法

**Comment by R29kTA** [comment]
> 你这种应该不要让状态栏透明，给状态栏设置一个背景色，然后不让布局侵入到状态栏，代码如下
> 
> ```kotlin
> UltimateBarX。与（这个）
>     .fitWindow（true）
>     .color（颜色。蓝色）
>     .applyStatusBar（）
> ```
> 
> 可以好好看看demo中各种效果的写法

谢谢
