### ISSUE TITLE
导航栏与页面之间有留白

### ISSUE THREAD

**Issue by OneUserName** [Zackratos/UltimateBarX#24]
![Capture20201231104419](https://user-images.githubusercontent.com/20177890/103391633-60025100-4b55-11eb-98b4-65ebb3234701.png)
![Capture20201231104708](https://user-images.githubusercontent.com/20177890/103391681-9b9d1b00-4b55-11eb-8198-d39318f4fcf6.png)

**Comment by hyy920109** [comment]
why close this issue?

**Comment by Pannarrow** [comment]
请教一下，怎么解决的呢
