### ISSUE TITLE
适配效果问题

### ISSUE THREAD

**Issue by onedreamyyc** [Zackratos/UltimateBarX#25]
UltimateBarX.with(this)
                .fitWindow(false)
                .transparent()
                .light(true)
                .applyStatusBar();
在vivox7 Android5.1系统上用上面的配置底部出现黑色的区域
UltimateBarX.with(this)
                .fitWindow(false)
                .transparent()
                .light(true)
                .applyNavigationBar();
换成这个底部黑色区域没了，但是状态栏颜色跟没适配之前一样了
这是我使用的方式有问题吗

**Comment by Zackratos** [comment]
应该是适配的问题，我没有你的那款手机，可以加我微信 Kratosbruce，一起看一下

**Comment by Zackratos** [comment]
应该修复了，可以用最新的 0.4.1 版本再试一下 @onedreamyyc
