### ISSUE TITLE
addStatusBarTopPadding(view)无法动态设置吗？

### ISSUE THREAD

**Issue by jiqianwen** [Zackratos/UltimateBarX#26]
或者说清除之前设置的view  add另一个view
CoordinatorLayout+AppBarLayout+CollapsingToolbarLayout使用的时候，我有个自己的标题栏，还有个系统的Toolbar 我需要根据展开收缩显示不同的标题布局，现在动态调用addStatusBarTopPadding(view)两个标题栏高度一直在叠加

**Comment by Zackratos** [comment]
只需要调用一次 `addStatusBarTopPadding(view)` 就行了，加了 padding 之后，还是之前的 view，直接控制 view 的 显示和隐藏就行了

**Comment by Zackratos** [comment]
如果还有问题，可以加我微信 kratosbruce 交流
