### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'.

### ISSUE THREAD

**Issue by jarvan11** [Zackratos/UltimateBarX#28]
https://github.com/guolindev/PermissionX/issues/5

**Comment by Zackratos** [comment]
这是啥意思，module 名称为 library 会跟其他的库冲突吗，要改 module 名称？

**Comment by AndroidJohnsonWang** [comment]
遇到同样的问题

**Comment by Zackratos** [comment]
改了 module 名称，可以尝试一下 0.6.0 版本 @jarvan11 @AndroidJohnsonWang
