### ISSUE TITLE
Fragment中调用,崩溃了.      调用截图和崩溃截图如下

### ISSUE THREAD

**Issue by lydlovezjr** [Zackratos/UltimateBarX#3]
<img width="711" alt="调用" src="https://user-images.githubusercontent.com/19246347/88249766-065d4700-ccd8-11ea-8fca-3cdf51a80799.png">
<img width="875" alt="bug" src="https://user-images.githubusercontent.com/19246347/88249767-078e7400-ccd8-11ea-961d-0fa89f33a52a.png">

**Comment by lydlovezjr** [comment]
使用的是最新的v0.2.0版本

**Comment by Zackratos** [comment]
你的 Fragment 是动态添加的吗？还是静态写在布局里面的？

**Comment by Zackratos** [comment]
你是使用 FragmentContainerView 作为 Fragment 的父布局的吗？

**Comment by Zackratos** [comment]
最新的 0.2.1 版本修改了 Fragment 的实现方式，在 Fragment 的根布局中实现，这个问题不存在了
@lydlovezjr
