### ISSUE TITLE
状态栏透明的情况下adjustResize无效

### ISSUE THREAD

**Issue by zzh3321** [Zackratos/UltimateBarX#30]
`UltimateBarX.with(this)
            .transparent()
            .light(true)
            .applyStatusBar()`
这个配置下会导致状态栏透明，透明会导致软键盘的adjustResize无效，不用这个库的情况下状态栏透明后在根布局加上android:fitsSystemWindows="true"可以解决，但是用这个库加上也没用，请问如何解决这个问题。

**Comment by Rethen** [comment]
我也遇到了，请问你后面怎么解决的？

**Comment by zzh3321** [comment]
> 我也遇到了，请问你后面怎么解决的？

还没解决，当时项目着急做，就先用隔壁的库了

**Comment by Rethen** [comment]
> > 我也遇到了，请问你后面怎么解决的？
> 
> 还没解决，当时项目着急做，就先用隔壁的库了

隔壁？能否介绍一下

**Comment by Rethen** [comment]
> > 我也遇到了，请问你后面怎么解决的？
> 
> 还没解决，当时项目着急做，就先用隔壁的库了

是不是ImmersionBar

**Comment by Zackratos** [comment]
问题已解决，可以使用 0.6.1 版本
@Rethen @zzh3321
