### ISSUE TITLE
单Activity，多Fragment的情况下的问题

### ISSUE THREAD

**Issue by twufive** [Zackratos/UltimateBarX#34]
只为Activity指定不侵入状态栏，Fragment正常使用；为Activity指定不侵入状态栏，再单独指定某一个Fragment不侵入状态栏，其他Fragment全部变成侵入状态栏。

**Comment by Zackratos** [comment]
「再单独指定某一个Fragment不侵入状态栏」，我猜你这句话说错了，你想说的应该是「再单独指定某一个Fragment侵入状态栏」

如果你是想表达这个意思，那确实是这样，因为单独制定某一个 Fragment 侵入状态栏的时候，会先让 他所在 的Activity 侵入状态栏，这个时候，如果你需要让其他 Fragment 不侵入状态栏，需要给 其他Fragment 单独指定不侵入状态栏

简单来说，就是你这种情况应该是单独对 每个 Fragment 进行设置，而不是对 Acitivty 进行设置
