### ISSUE TITLE
不能导入library

### ISSUE THREAD

**Issue by WenLonG12345** [Zackratos/UltimateBarX#37]
你好，感谢你的开源代码。可是当我试着导入您的library时，我发现我找不到 关于 UltimateBarX 的相关代码。
"Rebuild Project" 后 我得到一下的问题。
请问可以帮帮我吗？谢谢你。

![image](https://user-images.githubusercontent.com/39330565/125189071-00ee6900-e269-11eb-9f22-0277d062fa75.png)

**Comment by WenLonG12345** [comment]
我找到原因了， 是因为我拿掉了 `jcenter()`. 请问这个库是在` jcenter()` 的吗？

**Comment by Zackratos** [comment]
> 我找到原因了， 是因为我拿掉了 `jcenter()`. 请问这个库是在` jcenter()` 的吗？

是的，在 `jcenter()` 里的
