### ISSUE TITLE
Android10 状态栏会出现灰色遮罩，导航栏不会，看起来和历史issue应该是一个问题

### ISSUE THREAD

**Issue by yyj001** [Zackratos/UltimateBarX#42]
UltimateBarX.with(this)
      .transparent()
      .light(true)
      .applyStatusBar()

![download](https://user-images.githubusercontent.com/26819979/131276720-1b024867-da98-469c-8108-a0a3fe558d35.jpg)

**Comment by Zackratos** [comment]
什么手机，用的哪个版本

**Comment by yyj001** [comment]
一加7 pro, 刚刚换了0.7.1版本，试了一下还是有遮罩

**Comment by yyj001** [comment]
` UltimateBarX.statusBar(this)
      .transparent()
      .color(Color.TRANSPARENT)
      .colorRes(Color.TRANSPARENT)
      .light(true)
      .apply()`

**Comment by Zackratos** [comment]
这个跟 [issues5](https://github.com/Zackratos/UltimateBarX/issues/5) 应该不是同一个问题， [issues5](https://github.com/Zackratos/UltimateBarX/issues/5) 说的是导航栏有遮罩，而你的是状态栏，我感觉应该是你用了其他的状态栏的库的方法或者是代码里加了
```kotlin
window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS)
```
上面的代码在 `Android 5.0` 以上会导致状态栏有遮罩

**Comment by Zackratos** [comment]
[issues5](https://github.com/Zackratos/UltimateBarX/issues/5) 的遮罩是 `Android 10` 以上才有的，你也可以换个低版本的手机看一下是不是还有遮罩，如果还有，就说明不是同一个问题

**Comment by yyj001** [comment]
Android 8的手机上测没有遮罩😂，我可以再研究一下

**Comment by yyj001** [comment]
问题是由于在style添加了 <item name="android:windowTranslucentStatus">true</item> 引起

**Comment by Zackratos** [comment]
> 问题是由于在style添加了 `<item name="android:windowTranslucentStatus">true</item> `引起

不应该啊，我会重新给他设为 false，我再看一样
