### ISSUE TITLE
Android 9 以上要透明导航栏无解吗?

### ISSUE THREAD

**Issue by leanderli** [Zackratos/UltimateBarX#5]
我试了你的方法，跟我配置还是一样，导航栏始终无法透明，android 9/10/11 都是

**Comment by Zackratos** [comment]
具体的手机型号呢

**Comment by leanderli** [comment]
> 具体的手机型号呢

Android Q Android Studio模拟器，我自己的三星S10也是。不知道是不是我自己设置的window flag哪里有影响 我先再单独测试测试

**Comment by Zackratos** [comment]
你是怎么调用的，代码发出来我看一下

**Comment by leanderli** [comment]
> 你是怎么调用的，代码发出来我看一下

![Uploading QQ截图20200930170222.jpg…]()

**Comment by leanderli** [comment]
> 你是怎么调用的，代码发出来我看一下

![QQ截图20200930170222](https://user-images.githubusercontent.com/23739932/94780361-e7c3ac80-03fa-11eb-9d88-b8a4cb6b5c79.jpg)

**Comment by Zackratos** [comment]
好像确实无解，我试了一下，新版的系统都会有灰色的遮罩

**Comment by Attect** [comment]
styles或themes中设置
```
<item name="android:enforceStatusBarContrast" tools:targetApi="q">false</item>
<item name="android:enforceNavigationBarContrast" tools:targetApi="q">false</item>
```

**Comment by Zackratos** [comment]
> styles或themes中设置
> 
> ```
> <item name="android:enforceStatusBarContrast" tools:targetApi="q">false</item>
> <item name="android:enforceNavigationBarContrast" tools:targetApi="q">false</item>
> ```

厉害了，亲测有效，下个版本修复这个问题

**Comment by Zackratos** [comment]
@leanderli 问题解决，尝试一下最新版本
