### ISSUE TITLE
oppo手机有问题

### ISSUE THREAD

**Issue by shangmengmeng** [Zackratos/UltimateBarX#53]
![微信图片_20211101170149](https://user-images.githubusercontent.com/21009965/139647742-4980571d-fefd-4b83-b4d7-d9246bb0dceb.jpg)
小米手机隐藏掉底部虚拟导航也有问题

**Comment by shangmengmeng** [comment]
opp手机底部没有虚拟导航一片白色，去掉的话，小米手机就点不动下面自己写的底部导航，不成熟啊大兄弟

**Comment by Zackratos** [comment]
oppo 手机没有适配判断导航栏是否存在的方法，所以会有你说的问题，可以试一下 snapshot 版本，改变了判断导航栏的方法，不用根据 rom 类型来判断

**Comment by hyy920109** [comment]
> oppo 手机没有适配判断导航栏是否存在的方法，所以会有你说的问题，可以试一下 snapshot 版本，改变了判断导航栏的方法，不用根据 rom 类型来判断

snapshot 版本在哪？

**Comment by hyy920109** [comment]
> oppo 手机没有适配判断导航栏是否存在的方法，所以会有你说的问题，可以试一下 snapshot 版本，改变了判断导航栏的方法，不用根据 rom 类型来判断

切换到develop分之 就是snapshot版本吧。我看好想还是不行

**Comment by Zackratos** [comment]
> > oppo 手机没有适配判断导航栏是否存在的方法，所以会有你说的问题，可以试一下 snapshot 版本，改变了判断导航栏的方法，不用根据 rom 类型来判断
> 
> 切换到develop分之 就是snapshot版本吧。 snapshot 版本的lib库代码有吗 如何导入到本地呢

dev 分支，另外如果只需要设置状态栏不需要设置导航栏的话，可以升到 0.8.0 版本，用 `statusBarOnly` 方法替换 `statusBar` 方法，可以彻底解决导航栏的各种异常
导航栏的异常原因可以看 [issues44](https://github.com/Zackratos/UltimateBarX/issues/44#issuecomment-970164111) 里面的解释
