### ISSUE TITLE
当手机设置的手势操作时，无导航栏时 有问题 

### ISSUE THREAD

**Issue by lr784521** [Zackratos/UltimateBarX#7]
问题描述：
当手机设置的手势操作时，无导航栏时 使用插件设置状态栏时导航栏 会默认突然显示出来  在屏幕最低下 是一块黑色区域

正常导航栏不应该显示占位  原来UltimateBar 没有这种问题  

正常应该是有导航栏显示时 如果未设置 按系统默认处理  不用管  布局默认不侵入 导航栏   如果侵入会导致 APP菜单栏 与导航栏重叠   

当无导航栏  手势操控时  设置状态栏  不应该影响导航栏       

现在插件主要问题是  当手机没有导航栏时  设置状态栏  会出现导航栏 在底部一块黑色区域占位  很不友好  需要再次 设置导航栏透明才可以    但是当设置导航栏透明后  如果用户将导航栏放出 又会出现 布局入侵到导航栏  导航栏与APP底部菜单重叠问题

希望作者能处理下  非常感谢  

 UltimateBarX.create(UltimateBarX.STATUS_BAR)
                        .fitWindow(isLayoutInvade)   // 布局是否侵入状态栏（true 不侵入，false 侵入）
                        .bgColorRes(defaultStatusBarColor)  // 状态栏背景颜色（资源id）
                        .light(statueBarTextColor)   // 文字颜色  //true 黑色 false 白色
                        .apply(context);

**Comment by Zackratos** [comment]
全面屏手机确实有这样的问题，因为默认全面屏手机默认的导航栏是白色的，但是这里我给他默认设置成了黑色，后续会改一下这个问题

**Comment by Zackratos** [comment]
最新的 0.2.3 版本已经解决这个问题了，欢迎升级体验 @lr784521
